### ISSUE TITLE
How to converted darknet's weights to caffe's?

### ISSUE THREAD

**Issue by Zehaos** [xingwangsfu/caffe-yolo#1]
Hi, xingwang,
    I'm a green hand to caffe. I wonder how to convert the darknet's weights to caffe's? Thanks.

**Comment by xingwangsfu** [comment]
Hi,

Please check the update. Hope it helps.

**Comment by Zehaos** [comment]
It looks good! I will try it soon. Thank you very much~

**Comment by Zehaos** [comment]
Everything works fine!
