### ISSUE TITLE
How to prepare training data for caffe-yolo yolo_train_val.prototxt?

### ISSUE THREAD

**Issue by yangxian10** [xingwangsfu/caffe-yolo#2]
I can't find "result" layer in "yolo_train_val.prototxt". And I don't know how to prepare lmdb for caffe-yolo :)

**Comment by xingwangsfu** [comment]
Hi, 
I assume you want to train  yolo from scratch  in caffe. Unfortunately, current version doesn't support that. And I don't have free hands to do that now. It only supports the conversion from pre-trained yolo models to caffe models.  You can try to do that if you want. A easier way is to do the training with darknet. After that, do the conversion with caffe-yolo here.

Hope it answers your question.

**Comment by yangxian10** [comment]
Thanks for your reply. your darknet2caffe parameters conversion is excited :). With my GTX980, caffe-yolo can run 200 ms per image for testing.

**Comment by xingwangsfu** [comment]
Glad to hear that.
